name: default_lints
description: My default lints.
version: 1.0.0
repository: https://github.com/ahmed-osama-saad/default_lints.git

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  flutter_lints: ^2.0.0
  lints: ^2.0.0
  test: ^1.21.0
